/**:
  ros__parameters:
    simulated_frame_id: "base_link"
    origin_frame_id: "map"
    vehicle_model_type: "IDEAL_STEER_VEL"
    initialize_source: "INITIAL_POSE_TOPIC"
    timer_sampling_time_ms: 25
    add_measurement_noise: false
    vel_lim: 3.0
    vel_rate_lim: 2.0
    steer_lim: 0.7
    steer_rate_lim: 2.0
    acc_time_delay: 0.10
    acc_time_constant: 0.10
    steer_time_delay: 0.20
    steer_time_constant: 0.25
