/**:
  ros__parameters:
    wheel_radius: 0.085
    wheel_width: 0.041
    wheel_base: 0.5
    wheel_tread: 0.41
    front_overhang: 0.15
    rear_overhang: 0.15
    left_overhang: 0.05
    right_overhang: 0.05
    vehicle_height: 0.496
    max_steer_angle: 0.785

