/**:
  ros__parameters:
    wheel_radius: 0.15
    wheel_width: 0.05
    wheel_base: 0.42
    wheel_tread: 0.32
    front_overhang: 0.12
    rear_overhang: 0.10
    left_overhang: 0.04
    right_overhang: 0.04
    vehicle_height: 0.25
    max_steer_angle: 0.7
